monolog:
    channels: [deprecation]
    handlers:
        main:
            type: stream
            path: "php://stdout"
            level: info
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            channels: ["!deprecation"]
        console:
            type: console
            level: info
            process_psr_3_messages: false
            channels: ["!deprecation", "!doctrine", "!event"]
            verbosity_levels:
                VERBOSITY_NORMAL: INFO
