monolog:
    handlers:
        main:
            level: info
            type: stream
            path: "php://stderr"
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
