twig:
    cache: false
    #cache: '/mount/ephemeral/twig'
    # TODO get Twig cache working across local Docker + ECS
    # See https://github.com/outlandishideas/wpackagist/issues/368
    default_path: '%kernel.project_dir%/web/templates'
